In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [2]:
data=pd.read_csv('archive/emails.csv')

In [3]:
# print 5 values of dataset
data.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
data.shape

(5728, 2)

In [5]:
data.columns

Index(['text', 'spam'], dtype='object')

In [6]:
# check duplicates and drop them
data.drop_duplicates(inplace=True)

In [7]:
#show new shape of data
data.shape

(5695, 2)

In [8]:
#show number of missing data for each column
data.isnull().sum()

text    0
spam    0
dtype: int64

In [9]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [10]:
def process_text(text):
    # 1 Remove punctutaion
    # 2 Remove stopwords
    # 3 return a list of clean text words
    # 1
    nopunc=[char for char in text if char  not in string.punctuation]
    nopunc=''.join(nopunc)

    # 2
    clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

    # 3
    return  clean_words

In [11]:
# Show the tokenization
data['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [12]:

message4='hello world hello world play'
message5='test test test test one hello'
print(message4)
print()

from sklearn.feature_extraction.text import CountVectorizer
bow4=CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print(bow4)
print()

print(bow4.shape)

hello world hello world play

  (0, 0)	2
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1

(2, 5)


In [13]:
# convert a collection of text to a matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow=CountVectorizer(analyzer=process_text).fit_transform(data['text'])

In [14]:
# Train Test Spliting
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(messages_bow,data['spam'],test_size=0.20,random_state=0)

In [15]:
# Get the shape of messages
messages_bow.shape

(5695, 37229)

In [16]:
#Create and train the Native Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clasifier =MultinomialNB().fit(X_train,Y_train)

In [17]:
#print the predictions
print(clasifier.predict(X_train))

#print the actual value
print(Y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [18]:
# Evaluate the model on the training data
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=clasifier.predict(X_train)
print(classification_report(Y_train,pred))
print('Confusion Matrix:\n',confusion_matrix(Y_train,pred))
print()
print('Accuracy : ',accuracy_score(Y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556

Confusion Matrix:
 [[3445   12]
 [   1 1098]]

Accuracy :  0.9971466198419666


In [19]:
#print the predictions
print(clasifier.predict(X_test))

#print the actual value
print(Y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [20]:
# Evaluate the model on the testing data
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=clasifier.predict(X_test)
print(classification_report(Y_test,pred))
print('Confusion Matrix:\n',confusion_matrix(Y_test,pred))
print()
print('Accuracy : ',accuracy_score(Y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139

Confusion Matrix:
 [[862   8]
 [  1 268]]

Accuracy :  0.9920983318700615
